### ISSUE TITLE
Running studio with headless installs guide

### ISSUE THREAD

**Issue by marccampbell** [replicatedhq/help-center#291]
Create a doc that shows how to run studio w/ headless installs and testing upgrades that way

https://github.com/replicatedhq/studio/

Follow this doc https://help.replicated.com/docs/kb/developer-resources/automate-install/ for automating installations.

See https://github.com/replicatedhq/studio/#getting-started Use the https://get.replicated.com/studio easy install scripts for installing Replicated with Studio

See https://github.com/replicatedhq/studio/#iterating-on-your-yaml A new release can be created by simply updating $HOME/replicated/current.yaml

See https://help.replicated.com/api/replicatedctl/replicatedctl_app-release/ for updating replicated. You may have to source /etc/replicated.alias to get the replicatedctl command in your path. You should be able to use a combination of “replicatedctl app-release ls --pending -q” and “replicatedctl app-release apply --sequence=<sequence

**Comment by dexhorthy** [comment]
This feels a little stale -- closing
