### ISSUE TITLE
Helpcenter "Ship Overview" sidebar links to Troubleshooting and Ship Examples don't work

### ISSUE THREAD

**Issue by fshot** [replicatedhq/help-center#610]
Nothing happens if you click the bottom two links in the sidebar (troubleshooting or ship examples) while on the Ship Overview page at https://help.replicated.com/docs/ship/getting-started/overview/.

It looks like there _are_ pages in these sections, but the hrefs all point to the current page, and not the expected pages.

**Comment by dexhorthy** [comment]
This appears to have been fixed.
